services:
  odiakhaby_portfolio:
    image: odiakhaby_portfolio
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: odiakhaby_portfolio
    restart: unless-stopped
